FROM node:21-alpine3.18  

WORKDIR /frontend

  #-p kullaniyoruz. logs varsa yazma yoksa logs yerlestir
RUN mkdir -p logs   
RUN mkdir -p uploads   
RUN npm install

CMD ["npm" , "start"]

EXPOSE 8000