FROM node:current-alpine3.20

WORKDIR /frontend

  #-p kullaniyoruz. logs varsa yazma yoksa logs yerlestir
RUN mkdir -p logs   
RUN mkdir -p uploads   
RUN npm install

CMD ["npm" , "start"]

EXPOSE 8000