# compose kullanarak backend ve front end i birlestiriyoruz .yml

services:
  frontend:
    image: "docker-compose-frontend"
    build: ./frontend
    ports:
      - "5173:5173"
      - "3000:5173"
      - "80:5173"
    restart: on-failure
    depends_on:
      - backend
  backend:
    image: "docker-compose-backend"
    build: ./backend2
    ports:
      - "8000:8000"
    restart: on-failure

# docker compose up -d --build
  # -"3000:3000"
  #       -"5173:5173"
  #       -"3000:5173"
  #      - "80:5173"

